### ISSUE TITLE
Change InteractionLogic.cairo: add loop into follow function

### ISSUE THREAD

**Issue by ilyas-zkg** [ZK-Graph/mirror-starknet-zkgraph-protocol#2]
Current implementation gives an ability to follow only one Profile per execution.
We are requesting to add loop to follow function so that it'd possible to follow several Profiles per transaction.

Link to library: https://github.com/ZK-Graph/mirror-starknet-zkgraph-protocol/blob/main/contracts/libraries/InteractionLogic.cairo

**Comment by 4sm-ops** [comment]
Postponed
